version: '3.9'

services:
  proxy:
    image: nginx
    container_name: proxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "../proxy:/etc/nginx/templates"
      - "/etc/letsencrypt/live/testnet-explorer.xrone.network/privkey.pem:/etc/letsencrypt/live/testnet-explorer.xrone.network/privkey.pem:ro"
      - "/etc/letsencrypt/live/testnet-explorer.xrone.network/fullchain.pem:/etc/letsencrypt/live/testnet-explorer.xrone.network/fullchain.pem:ro"
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
    ports:
      - "443:443"
      - "8080:8080"
      - "8081:8081"
